[system]
selection_conf = conf/selection_1.ini
sr_data_dir = /mnt/users/deaglan/symbolic_regression/iob-attenuation/symbolic_regression/data
fit_dir = fits
version_num = 36

[data]
in_param = iob
seed = 0
ntrain = 1_500
nval = 750
ntest = 750
lambda_V = 0.5542
npar = 4
fit_log = False
lam_max = 1
lam_min = 0.1
lam_bump_min = 0.166
lam_bump_max = 0.277
keep_region = all
; keep_region one of 'all', 'outer', 'bump'
; lam_trans = 0.3827
; f_subsample = 3
subtract_outer = True

[operon]
allowed_symbols = add,sub,mul,div,sqrt,square,log,pow,tanh,constant,variable
epsilon = 1e-2
max_length = 50
time_limit = 20
objectives=['rmse', 'length']
max_evaluations=1e12
generations=1e12
