# This file is automatically generated by processing_fun.reparameterise
# Do not edit this file directly.

import numpy as np

def compute_initial_B(IOB):
    b = [3.207993816608, 0.981869, 163.182144, 596.44519, 3059.672607, 15.086555, 9.938943506881, 0.101915, 0.981869, 74.840126, 54.567383, 18.352127, 4.385856, 3.134392, 25.086458, 9.698587]
    B0 = -IOB[0]*b[0] + b[7]
    B1 = -b[1]*(-IOB[0]*b[2] - IOB[6]*b[3] - IOB[7]*b[4] - b[5])
    B2 = IOB[0]*b[9] + IOB[1]*b[10]
    return B0, B1, B2

def compute_Av(x, B0, B1, B2):
    a = [18.352127, 4.385856, -9.93894350688100, 25.086458, 0.981869, -3.13439200000000, -9.69858700000000]
    A_over_Av = B0 + B1*np.exp(a[2]*x**2) + a[4]*(B2 + a[0]*x)/(np.sqrt((a[1]*x + a[5])**4 + 1)*np.sqrt((a[3]*x + a[6])**2 + 1))
    return A_over_Av
