# This file is automatically generated by processing_fun.reparameterise
# Do not edit this file directly.

import numpy as np

def compute_initial_B(IOB):
    c = [1.000648, 45.120201, 208.741272, 2.214609, 11.210193, 1.380509, 22.421267, 5.736165, 3.953059, 5.040799, 7.073277, 3.570695, 9.125808, 1.000648, 21.685377, 1.474194, 1.215716, 16.786709, 6.730947, 0.002466]
    B0 = c[13]*(IOB[0]*c[14] + c[15])
    B1 = IOB[1]*c[16]
    B2 = IOB[0]*c[3] - IOB[2]*c[4]
    B3 = (IOB[1]*c[6] + np.exp(IOB[0]*c[7]))*np.exp(-IOB[2]*c[10])
    B4 = -IOB[1]*c[9]
    B5 = -IOB[1]*c[11]
    return B0, B1, B2, B3, B4, B5

def compute_Av(x, B0, B1, B2, B3, B4, B5):
    a = [-0.00246600000000000, -9.12580800000000, -6.73094700000000, 1.000648, 1.380509, 45.120201, 16.786709, -208.741272000000, -3.95305900000000]
    A_over_Av = B0*np.exp(B1 - (a[2] + a[6]*x)**2) + a[0] + a[3]*(a[5] + a[7]*x)*(B2 + B3*(a[8]*x + np.exp(B4)) + a[4]*x)*np.exp(B5 + a[1]*x)
    return A_over_Av
