# This file is automatically generated by processing_fun.reparameterise
# Do not edit this file directly.

import numpy as np

def compute_initial_B(IOB):
    b = [3.207993816608, 0.981869, 163.182144, 596.44519, 3059.672607, 15.086555, 9.938943506881, 0.101915, 0.981869, 74.840126, 54.567383, 18.352127, 4.385856, 3.134392, 25.086458, 9.698587]
    B0 = -IOB[0]*c0 + c7
    B1 = -c1*(-IOB[0]*c2 - IOB[6]*c3 - IOB[7]*c4 - c5)
    B2 = IOB[0]*c9 + IOB[1]*c10
    return B0, B1, B2

def compute_Av(x, B0, B1, B2):
    a = [25.086458, -9.93894350688100, 0.981869, 18.352127, -3.13439200000000, -9.69858700000000, 4.385856]
    A_over_Av = B0 + B1*np.exp(a[1]*x**2) + a[2]*(B2 + a[3]*x)/(np.sqrt((a[4] + a[6]*x)**4 + 1)*np.sqrt((a[0]*x + a[5])**2 + 1))
    return A_over_Av
